# Generated by Django 3.2.7 on 2021-10-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
